CREATE TABLE IF NOT EXISTS submissions (
    id SERIAL PRIMARY KEY,
    landpage VARCHAR(10) NOT NULL,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
